repos:
- repo: local
  
  
  
  hooks:

  - id: isort
    name: isort
    entry: isort --settings-file ./.isort.cfg .
    language: system
    types: [python]

  - id: black
    name: black
    entry: black
    language: system
    types: [python]
    args: [
            --line-length=80
        ]



  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]


  